<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OpsAssetsSeeder extends Seeder
{
    public function run(): void
    {
        // products
        DB::table('products')->insert([
            ['title' => 'Round Dining Table', 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ', 'category' => '', 'price' => 200.00, 'qty' => 5, 'media_url' => 'uploads/1755526951_Tate60inRndDiningTbl3QSSF23_3D_1200x1200.webp', 'item_id' => 1316, 'cost' => 200.00, 'location' => '', 'department' => '', 'type' => 'Intangible', 'status' => 'In Use', 'useful_life' => 6, 'depreciation_rate' => 16.67, 'registration_date' => '2025-08-18', 'registration_id' => 'REG-20250818-5669', 'asset_id' => 'AST-202508-52229', 'requestor' => '', 'approver' => '', 'assigned_personnel' => '', 'asset_group' => 'Non-Current', 'supplier_vendor' => ''],
            ['title' => 'GeForce RTX 5090', 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ', 'category' => '', 'price' => 40000.00, 'qty' => 5, 'media_url' => 'uploads/1755527045_Png.png', 'item_id' => 1317, 'cost' => 40000.00, 'location' => '', 'department' => '', 'type' => 'Intangible', 'status' => 'In Use', 'useful_life' => 6, 'depreciation_rate' => 16.67, 'registration_date' => '2025-08-18', 'registration_id' => 'REG-20250818-2643', 'asset_id' => 'AST-202508-32673', 'requestor' => '', 'approver' => '', 'assigned_personnel' => '', 'asset_group' => 'Non-Current', 'supplier_vendor' => ''],
            ['title' => 'Tsunami Massage', 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ', 'category' => '', 'price' => 1000.00, 'qty' => 5, 'media_url' => 'uploads/1755527135_TsunamiMassage_540x.jpg', 'item_id' => 1318, 'cost' => 1000.00, 'location' => '', 'department' => '', 'type' => 'Intangible', 'status' => 'In Use', 'useful_life' => 10, 'depreciation_rate' => 10.00, 'registration_date' => '2025-08-18', 'registration_id' => 'REG-20250818-7472', 'asset_id' => 'AST-202508-28786', 'requestor' => '', 'approver' => '', 'assigned_personnel' => '', 'asset_group' => 'Non-Current', 'supplier_vendor' => ''],
            ['title' => 'IPS Gaming Monitor', 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ', 'category' => '', 'price' => 3000.00, 'qty' => 15, 'media_url' => 'uploads/1755527248_27M1N5200P_71-IMS-en_PH_800x.webp', 'item_id' => 1319, 'cost' => 3000.00, 'location' => '', 'department' => '', 'type' => 'Intangible', 'status' => 'In Use', 'useful_life' => 5, 'depreciation_rate' => 20.00, 'registration_date' => '2025-08-18', 'registration_id' => 'REG-20250818-7234', 'asset_id' => 'AST-202508-27509', 'requestor' => '', 'approver' => '', 'assigned_personnel' => '', 'asset_group' => 'Non-Current', 'supplier_vendor' => ''],
            ['title' => 'Swedish Massage', 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ', 'category' => 'Hygiene', 'price' => 0.00, 'qty' => 1, 'media_url' => 'uploads/1755527344_SwedishMassage_23ab0c61-553d-4979-a0ed-738cccbd65be_540x.jpg', 'item_id' => 1320, 'cost' => 1000.00, 'location' => '0', 'department' => 'Stafify', 'type' => 'Intangible', 'status' => 'In Use', 'useful_life' => 7, 'depreciation_rate' => 14.29, 'registration_date' => '2025-08-18', 'registration_id' => 'REG-20250818-7955', 'asset_id' => 'AST-202508-91333', 'requestor' => 'Amil Musa', 'approver' => 'Allen Lim', 'assigned_personnel' => 'Miko Oliva', 'asset_group' => 'Non-Current', 'supplier_vendor' => null],
            ['title' => 'Office Desk', 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ', 'category' => 'Furniture', 'price' => 0.00, 'qty' => 6, 'media_url' => 'uploads/1755527468_jefferson2_1200x1200.webp', 'item_id' => 1322, 'cost' => 1200.00, 'location' => '0', 'department' => 'Spasify', 'type' => 'Tangible', 'status' => 'In Use', 'useful_life' => 8, 'depreciation_rate' => 12.50, 'registration_date' => '2025-08-18', 'registration_id' => 'REG-20250818-3546', 'asset_id' => 'AST-202508-38429', 'requestor' => 'Alsherette Ramos', 'approver' => 'Allen Lim', 'assigned_personnel' => 'Justine Dimalanta', 'asset_group' => 'Current', 'supplier_vendor' => null],
        ]);

        // asset_assignments
        DB::table('asset_assignments')->insert([
            ['id' => 1, 'request_date' => '2025-05-07 16:00:00', 'assignment_request_id' => 'AR-681c5b6c0fbed', 'requestor_name' => '123', 'location' => '123', 'department' => '123', 'asset_id' => 'Asset-001', 'reason' => '123', 'proposed_return_date' => '2025-05-08', 'status' => 'Rejected', 'approver_comment' => 'pass', 'reviewed_by' => 'Justine Dimalanta', 'reviewed_date' => '2025-05-08 15:25:35', 'assigned_to' => 'ewan', 'assignment_date' => null, 'expected_return_date' => null, 'asset_condition_assignment' => 'In use', 'assignment_notes' => 'xd', 'returned_by' => null, 'returned_date' => null, 'return_condition' => null, 'return_comment' => null, 'user_returned_by' => null, 'user_returned_date' => null, 'user_return_condition' => null, 'user_return_comment' => null, 'archived' => 0],
            ['id' => 2, 'request_date' => '2025-10-21 16:00:00', 'assignment_request_id' => 'AR-68f8daf464ab0', 'requestor_name' => 'Justine', 'location' => 'test', 'department' => 'test', 'asset_id' => 'Asset-002', 'reason' => 'test', 'proposed_return_date' => '2025-10-22', 'status' => 'Pending', 'approver_comment' => null, 'reviewed_by' => null, 'reviewed_date' => null, 'assigned_to' => null, 'assignment_date' => null, 'expected_return_date' => null, 'asset_condition_assignment' => null, 'assignment_notes' => null, 'returned_by' => null, 'returned_date' => null, 'return_condition' => null, 'return_comment' => null, 'user_returned_by' => '', 'user_returned_date' => null, 'user_return_condition' => 'Available', 'user_return_comment' => 'test', 'archived' => 0],
        ]);

        // purchase_requests
        DB::table('purchase_requests')->insert([
            ['id' => 1, 'request_date' => '2025-05-08', 'request_id' => 'REQ-20250508-6f099', 'requestor_name' => '123', 'requestor_location' => '123', 'requestor_department' => '123', 'asset_type' => '312', 'asset_category' => '123', 'asset_name' => '123132', 'asset_description' => '13123', 'asset_quantity' => 1132, 'estimated_cost' => 10.00, 'supplier_vendor' => '123', 'status' => 'Pending', 'approver_comment' => null, 'reviewed_by' => null, 'reviewed_date' => null, 'archived' => 1],
            ['id' => 2, 'request_date' => '2025-10-22', 'request_id' => 'REQ-20251022-1ff04', 'requestor_name' => 'Justine DImalanta', 'requestor_location' => 'test', 'requestor_department' => 'test', 'asset_type' => 'test', 'asset_category' => 'test', 'asset_name' => 'test', 'asset_description' => 'test', 'asset_quantity' => 5, 'estimated_cost' => 100.00, 'supplier_vendor' => 'Stafify', 'status' => 'Approved', 'approver_comment' => 'ocakes', 'reviewed_by' => 'Miko2', 'reviewed_date' => '2025-10-22 21:11:44', 'archived' => 0],
            ['id' => 3, 'request_date' => '2025-10-22', 'request_id' => 'REQ-20251022-d2f85', 'requestor_name' => 'test', 'requestor_location' => 'test', 'requestor_department' => 'test', 'asset_type' => 'test', 'asset_category' => 'test', 'asset_name' => 'test', 'asset_description' => 'test', 'asset_quantity' => 1, 'estimated_cost' => 50.00, 'supplier_vendor' => 'test', 'status' => 'Approved', 'approver_comment' => 'test', 'reviewed_by' => 'Miko1', 'reviewed_date' => '2025-10-22 21:17:08', 'archived' => 0],
        ]);

        // purchase_orders
        DB::table('purchase_orders')->insert([
            ['id' => 124, 'po_number' => 'PO-20251022-17256', 'order_date' => '2025-10-22', 'purchase_request_id' => 'REQ-20251022-d2f85', 'delivery_location' => 'test', 'asset_type' => 'test', 'asset_category' => 'test', 'asset_name' => 'XD', 'asset_description' => 'test', 'asset_quantity' => 5, 'cost' => 122.00, 'supplier_name' => 'Justine', 'preferred_payment_method' => 'Maya', 'requested_payment_terms' => 'weqwe', 'expected_delivery_date' => '2025-10-30', 'order_placed' => '2025-10-22 21:33:33', 'payment_confirmed' => null, 'shipped_out' => null, 'order_received' => null, 'completed' => null, 'returned' => null, 'status' => null, 'notes' => null],
        ]);
    }
}


